# Generated by Django 2.2.4 on 2019-08-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('ddes', models.CharField(max_length=30)),
                ('dproject', models.CharField(max_length=30)),
                ('ddoj', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=30)),
                ('tdes', models.CharField(max_length=30)),
                ('tproject', models.CharField(max_length=30)),
                ('tdoj', models.DateField()),
            ],
        ),
    ]
