# Generated by Django 2.2.4 on 2019-08-30 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='university',
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.University'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='department',
            name='college',
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ManyToManyField(to='app.College'),
        ),
    ]
