# Generated by Django 2.2.4 on 2019-09-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(max_length=20)),
                ('vendor_comp_name', models.CharField(max_length=40)),
                ('vendor_name', models.CharField(max_length=30)),
                ('vendor_cat', models.CharField(max_length=20)),
                ('vendor_addr', models.TextField()),
                ('vendor_gst_no', models.CharField(max_length=20)),
                ('vendor_mob_no', models.CharField(max_length=15)),
                ('vendor_office_no', models.CharField(max_length=15)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('vendor_pan_no', models.CharField(max_length=20)),
                ('vendor_city', models.CharField(max_length=20)),
                ('vendor_pin', models.IntegerField()),
                ('vendor_state', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'vendor_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_code', models.CharField(max_length=15)),
                ('prod_name', models.CharField(max_length=40)),
                ('prod_tag', models.CharField(max_length=40)),
                ('prod_tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxapp.TaxMaster')),
            ],
            options={
                'db_table': 'product_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('prod_invent_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_total_quantity', models.IntegerField()),
                ('prod_sold_quantity', models.IntegerField()),
                ('prod_amount_without_tax', models.FloatField()),
                ('prod_stock_remaining', models.IntegerField()),
                ('prod_current_selling_price', models.FloatField()),
                ('prod_location', models.CharField(max_length=45)),
                ('prod_dispatch_date', models.DateField()),
                ('prod_received_date', models.DateField()),
                ('invent_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.ProductMaster')),
                ('invent_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventoryapp.VendorDetails')),
            ],
            options={
                'db_table': 'product_inventory',
                'managed': True,
            },
        ),
    ]
