# Generated by Django 2.2.4 on 2019-08-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Born',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=30)),
                ('bdate', models.DateField()),
                ('bcity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=30)),
                ('htype', models.CharField(max_length=30)),
                ('hcity', models.CharField(max_length=30)),
                ('haddr', models.CharField(max_length=60)),
            ],
        ),
    ]
