# Generated by Django 2.2.4 on 2019-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='scollege',
        ),
        migrations.AddField(
            model_name='student',
            name='smarks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
