# Generated by Django 2.2.4 on 2019-08-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=30)),
                ('ledu', models.CharField(max_length=30)),
                ('lfac', models.CharField(max_length=30)),
                ('ldoj', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pedu', models.CharField(max_length=30)),
                ('pfac', models.CharField(max_length=30)),
                ('pdoj', models.DateField()),
            ],
        ),
    ]
